### ISSUE TITLE
Error: Self referencing loop detected for property 'Module'

### ISSUE THREAD

**Issue by dmitriy-shleht** [GokGokalp/NLog.Web.AspNetCore.Targets.Gelf#13]
Hi,
I can not understand why an error occurs in `internalLogFile`:

```
2019-10-23 12:53:29.3476 Error Error has been raised. Exception: Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'Module' with type 'System.Reflection.RuntimeModule'. Path 'Module.Assembly.EntryPoint'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at NLog.Web.AspNetCore.Targets.Gelf.GelfConverter.AddAdditionalField(IDictionary`2 jObject, KeyValuePair`2 property)
   at NLog.Web.AspNetCore.Targets.Gelf.GelfConverter.GetGelfJson(LogEventInfo logEventInfo, String facility)
   at NLog.Web.AspNetCore.Targets.Gelf.GelfTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
```

I have tried all versions. Sample project attached.
[WebApplication1.zip](https://github.com/GokGokalp/NLog.Web.AspNetCore.Targets.Gelf/files/3761984/WebApplication1.zip)

**Comment by snakefoot** [comment]
Alternative change to [NLog.GelfLayout](https://www.nuget.org/packages/NLog.GelfLayout). You can find examples how to combine it with UDP / TCP / HTTP here:

- https://github.com/farzadpanahi/NLog.GelfLayout/

There is also [NLog.Targets.Network](https://www.nuget.org/packages/NLog.Targets.Network)-nuget-package introduced with NLog v6 that includes [GELF-target](https://github.com/NLog/NLog/wiki/Gelf-target) (Without dependency on Newtonsoft.Json)
