### ISSUE TITLE
Custom Layout Issue

### ISSUE THREAD

**Issue by efaruk** [GokGokalp/NLog.Web.AspNetCore.Targets.Gelf#3]
Hi I tried both disabling and enabling `SendLastFormatParameter` but still it's not working.

```
<target xsi:type="Gelf" name="graylog" 
                endpoint="udp://127.0.0.1:12201" 
                facility="my-application" 
                SendLastFormatParameter="true/false"
                layout="[${longdate}][${environment:ASPNETCORE_ENVIRONMENT}][${machinename}][${level}][${logger}] [${message}] [${exception:format=ToString,Data:maxInnerExceptionLevel=10}] [${stacktrace:format=Raw:topFrames=10}]" /
```>

> 2018-04-20 14:12:10.7910 Error Error has been raised. Exception: Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'ManifestModule' with type 'System.Reflection.RuntimeModule'. Path 'InnerException.TargetSite.Module.Assembly'.
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
>    at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
>    at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
>    at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
>    at Newtonsoft.Json.Linq.JToken.FromObject(Object o)
>    at NLog.Web.AspNetCore.Targets.Gelf.GelfConverter.AddAdditionalField(IDictionary`2 jObject, KeyValuePair`2 property)
>    at NLog.Web.AspNetCore.Targets.Gelf.GelfConverter.GetGelfJson(LogEventInfo logEventInfo, String facility)
>    at NLog.Web.AspNetCore.Targets.Gelf.GelfTarget.Write(LogEventInfo logEvent)
>    at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)

**Comment by GokGokalp** [comment]
Hi.
Instead of layout, could you please change your **NLog GELF** config as follows:

`    <target xsi:type="Gelf" name="graylog"
                endpoint="udp://localhost:12201"
                facility="my-application"
                SendLastFormatParameter="false">
      
      <parameter name="Environment" layout="${environment:ASPNETCORE_ENVIRONMENT}"/>
      <parameter name="MachineName" layout="${machinename}"/>
    </target>`

Regards.

**Comment by efaruk** [comment]
@ptupitsyn could you please take a look?

**Comment by GokGokalp** [comment]
@ptupitsyn ping? :)

**Comment by ptupitsyn** [comment]
Works for me. We can close this I guess. Thanks!
